name: Cross-compile and publish bindings for all targets

on:
  push:

  workflow_dispatch:

env:
  RUST_VERSION: 1.78

jobs:
  generate-bindings:
    uses: ./.github/workflows/gen-bindings-go.yaml
    with:
      rust_version: ${{ env.RUST_VERSION }}

  build-libraries:
    uses: ./.github/workflows/build-libraries.yaml
    with:
      rust_version: ${{ env.RUST_VERSION }}

  publish-ldk-node-go:
    needs:
      - generate-bindings
      - build-libraries
    uses: ./.github/workflows/publish-bindings-go.yaml
    secrets:
      LDK_NODE_GO_DEPLOY_KEY: ${{ secrets.LDK_NODE_GO_DEPLOY_KEY }}
